### PR TITLE
Results fix and enhance

### PR DESCRIPTION
**Pull request by narasimhan-v**

### CODE REVIEW

**Comment by narasimhan-v** [comment]
```
# python avocado-setup.py --run-suite host_test
08:05:10 INFO    : Check for environment
08:05:10 INFO    : Creating temporary mux dir
08:05:21 INFO    : install packages via pip interface
08:05:23 INFO    : 
08:05:23 INFO    : Running Host Tests Suite test_pci_info_lsvpd
08:05:23 INFO    : Running: /usr/bin/avocado run avocado-misc-tests/io/pci/pci_info_lsvpd.py --force-job-id 85a59d8bd06649b0ef6b4e69fde561687ae00ff1  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 85a59d8bd06649b0ef6b4e69fde561687ae00ff1
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-85a59d8/job.log
 (1/1) avocado-misc-tests/io/pci/pci_info_lsvpd.py:PciLsvpdInfo.test: PASS (8.07 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 8.11 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-85a59d8/results.html
08:05:32 INFO    : 
08:05:32 INFO    : 
08:05:32 INFO    : Running Host Tests Suite test_dlpar_dlpar
08:05:32 INFO    : Running: /usr/bin/avocado run avocado-misc-tests/io/pci/dlpar.py -m /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/pci/dlpar.py.data/dlpar.yaml --force-job-id e479f8eb6bb8c146a6bff21ea5a7289c7a89f0ef  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : e479f8eb6bb8c146a6bff21ea5a7289c7a89f0ef
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-e479f8e/job.log
 (1/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_dlpar;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
 (2/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_pci;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
 (3/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_phb;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 3
JOB TIME   : 4.86 s
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-e479f8e/results.html
08:05:37 INFO    : 
08:05:37 INFO    : Summary of test results can be found below:
TestSuite                                                                   TestRun    Summary             
 
host_test_pci_info_lsvpd                                                    Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-85a59d8/job.log
              ||  TOTAL 1  |  PASS 1  |  FAIL 0  |  CANCEL 0  ||
 
host_test_dlpar_dlpar                                                       Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-e479f8e/job.log
              ||  TOTAL 3  |  PASS 0  |  FAIL 0  |  CANCEL 3  ||
08:05:37 INFO    : Removing temporary mux dir
```

**Comment by sathnaga** [comment]
@narasimhan-v any background to why summary dashboard needs now pass/fails stats, is there any specific usecase? we can discuss more and see how can we solve.
One suggestion, seeing results.json has a super set of values, we could rather use that file itself in other layers...that would be scalable  aswell...

**Comment by narasimhan-v** [comment]
@sathnaga 

Background: The `avocado run` command's results are not logged anywhere. So, we provide users as much data as possible. Since results.json has the values, we are using them to print.
Also, there are many use cases that can evolve with wrapper having this data. We can take more decisions based on the results, if needed.
My idea is, if there are related tests in a cfg, and one test fails, we can decide not to run the other tests.
There can be other use cases also coming in, once we have such data.


Regarding using results.json for most values, yes that is what I also thought. So started with result status for now.

**Comment by sathnaga** [comment]
> @sathnaga
> 
> Background: The `avocado run` command's results are not logged anywhere. 
it is logged here to user right...
```
JOB ID     : e479f8eb6bb8c146a6bff21ea5a7289c7a89f0ef
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-e479f8e/job.log
 (1/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_dlpar;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
 (2/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_pci;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
 (3/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_phb;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 3
JOB TIME   : 4.86 s
```

So, we provide users as much data as possible. Since results.json has the values, we are using them to print.
> Also, there are many use cases that can evolve with wrapper having this data. We can take more decisions based on the results, if needed.
> My idea is, if there are related tests in a cfg, and one test fails, we can decide not to run the other tests.
So, the intention is to use fail-early?
if then we should be using this in our extra params, if needed we can introduce wrapper param aswell explicitly, `--failfast {on,off}`

> There can be other use cases also coming in, once we have such data.
> 

> Regarding using results.json for most values, yes that is what I also thought. So started with result status for now.
Better to avoid re-printing the data which are printing to user already... even result summary itself unwanted we can get rid of it and think of directly using result.json in other layers, so that it is would be good, let's discuss more on the usecases and come up with better way.

**Comment by narasimhan-v** [comment]
> 
> it is logged here to user right...
> 
> ```
> JOB ID     : e479f8eb6bb8c146a6bff21ea5a7289c7a89f0ef
> JOB LOG    : /root/avocado-fvt-wrapper/results/job-2019-05-23T08.05-e479f8e/job.log
>  (1/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_dlpar;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
>  (2/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_pci;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
>  (3/3) avocado-misc-tests/io/pci/dlpar.py:DlparPci.test_drmgr_phb;hmc_pwd-hmc_username-lpar_2-num_of_dlpar-pci_device-url-f49c: CANCEL: ksh is needed for the test to be run (1.58 s)
> RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 3
> JOB TIME   : 4.86 s
> ```

This is not logged to the avocado-wrapper.log
Also, the idea to print everything in the summary is, to have a holistic view in the summary.

> 
> So, we provide users as much data as possible. Since results.json has the values, we are using them to print.
> 
> > Also, there are many use cases that can evolve with wrapper having this data. We can take more decisions based on the results, if needed.
> > My idea is, if there are related tests in a cfg, and one test fails, we can decide not to run the other tests.
> 
> So, the intention is to use fail-early?
> if then we should be using this in our extra params, if needed we can introduce wrapper param aswell explicitly, `--failfast {on,off}`

Yes, that is the first idea I wanted to work on, for which these results are needed.

> 
> > There can be other use cases also coming in, once we have such data.
> 
> > Regarding using results.json for most values, yes that is what I also thought. So started with result status for now.
> 
> Better to avoid re-printing the data which are printing to user already... even result summary itself unwanted we can get rid of it and think of directly using result.json in other layers, let's discuss more on the usecases and come up with better way.

The reason summary is printed is:
1. The `avocado run` command's output is not logged
2. If there are multiple cfg run, it is too much of scrolling (minor issue, but a use case neverthless)

And yes, we can use the result.json more effectively.

**Comment by narasimhan-v** [comment]
@sathnaga closing this, and as discussed, will handle each feature / fix separately.

**Pull request closed without merging**
